name: CI/CD Docker

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest ./app

      - name: Run container (test)
        run: |
          docker run -d --name movieflix_test -p 8001:8000 ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
          sleep 3
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8001/health || true)
          if [ "$STATUS" != "200" ]; then
            docker logs movieflix_test || true
            exit 1
          fi
          docker stop movieflix_test
          docker rm movieflix_test

      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.IMAGE_NAME }}:latest
